version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # Install your project's dependencies
      - npm install
  build:
    commands:
      # Build your Vue.js application for production
      - npm run build

artifacts:
  files:
    # Include all files in the dist directory
    - '**/*'
  # Specify the directory where build output is stored
  base-directory: 'dist'